repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^template\.yaml$
      - id: check-added-large-files
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.35.1 # Use the latest stable version
    hooks:
      - id: cfn-lint
        files: ^template\.yaml$
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort
        args: [--in-place]
        files: ^samconfig\.toml$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
