AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-creds-oidc
  
  Sample SAM Template for aws-creds-oidc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  AwsCredsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./
      Handler: cmd/lambda
      Runtime: provided.al2
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        AwsCreds:
          Type: Api
          Properties:
            Path: /aws-creds
            Method: POST
        Callback:
          Type: Api
          Properties:
            Path: /callback
            Method: GET
      Environment:
        Variables:
          SESSION_TABLE: !Ref SessionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRoleWithWebIdentity
              Resource: "*"

  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aws-creds-oidc-sessions
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

Outputs:
  AwsCredsAPI:
    Description: "API Gateway endpoint URL for aws-creds and callback endpoints"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AwsCredsFunction:
    Description: "Lambda Function ARN for aws-creds-oidc"
    Value: !GetAtt AwsCredsFunction.Arn
  SessionTable:
    Description: "DynamoDB Table for session storage"
    Value: !Ref SessionTable
