AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-creds-oidc

  AWS SAM template for a serverless Go application that securely vends AWS credentials using OIDC authentication.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  AwsCredsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./
      Handler: cmd/aws-creds-lambda
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /auth
            Method: GET
        Creds:
          Type: Api
          Properties:
            Path: /creds
            Method: POST
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRoleWithWebIdentity
              Resource: "*"
      Environment:
        Variables:
          OIDC_ISSUER: !Ref OIDCIssuer
          OIDC_CLIENT_ID: !Ref OIDCClientId
          OIDC_CLIENT_SECRET: !Ref OIDCClientSecret
          OIDC_REDIRECT_URI: !Ref OIDCRedirectUri

Outputs:
  AwsCredsAPI:
    Description: "API Gateway endpoint URL for auth and creds endpoints"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AwsCredsFunction:
    Description: "Lambda Function ARN for aws-creds-oidc"
    Value: !GetAtt AwsCredsFunction.Arn

Parameters:
  OIDCIssuer:
    Type: String
    Description: OIDC Issuer URL
    Default: ""
  OIDCClientId:
    Type: String
    Description: OIDC Client ID
    Default: ""
  OIDCClientSecret:
    Type: String
    Description: OIDC Client Secret
    Default: ""
